version: '2'
services:
    jhipsterpwatestapplication-postgresql:
        image: postgres:10.4
        # volumes:
        #     - ~/volumes/jhipster/jhipsterPWATestApplication/postgresql/:/var/lib/postgresql/data/
        environment:
            - POSTGRES_USER=jhipsterPWATestApplication
            - POSTGRES_PASSWORD=
        ports:
            - 5432:5432
